#!/usr/bin/env python

#         __________________________
#         |____C_O_P_Y_R_I_G_H_T___|
#         |                        |
#         |  (c) NIWA, 2008-2010   |
#         | Contact: Hilary Oliver |
#         |  h.oliver@niwa.co.nz   |
#         |    +64-4-386 0461      |
#         |________________________|


""" 
Documentation
"""

import sys
import cylc_mode
from optparse import OptionParser
from task_message import message
from task_lock import task_lock

usage = """cylc task-failed [options] [REASON]

This is part of the cylc external task interface.

Release my lock to the lockserver, and report that I have failed.

Arguments:
    REASON        - message explaining why the task failed."""

parser = OptionParser( usage )

( options, args ) = parser.parse_args()

if len( args ) == 0:
    reason = None
else:
    reason = ' '.join( args )

if not cylc_mode.mode().is_raw():
    try:
        if not task_lock().release():
            msg = "FAILED TO RELEASE TASK LOCK"
            print >> sys.stderr, msg
            message( msg, 'WARNING' ).send()
            # this implies a bug in the lockserver, maybe? 
    except:
        # failed to connect to lockserver
        msg = "FAILED TO CONNECT TO A LOCKSERVER"
        message( msg, 'WARNING' ).send()
        print >> sys.stderr, msg
 
message( reason ).send_failed()
